---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: plexcloudmusic/reapply-pipelines

inputs:
- name: git_docker_image

run:
  path: git_docker_image/tasks/apply_pipeline/task.sh
